### ISSUE TITLE
 error C2491: “OgreBites::ApplicationContextQt::staticMetaObject”:  dllimport static member is not allowed in moc_OgreApplicationContextQt.cpp

### ISSUE THREAD

**Issue by ronaldpan** [OGRECave/ogitor#30] opened 2020-04-22 10:17 UTC
error C2491: “OgreBites::ApplicationContextQt::staticMetaObject”:  dllimport static member is not allowed in moc_OgreApplicationContextQt.cpp

**Comment by paroj** [comment] 2020-04-23 17:56
duplicate of https://github.com/OGRECave/ogre/issues/1550

**Closed by paroj** 2020-04-23 17:56 UTC
